### ISSUE TITLE
DoubleByteBufferTest fails on branch-4.6

### ISSUE THREAD

**Issue by eolivelli** [apache/bookkeeper#1001]
**BUG REPORT**

1. Please describe the issue you observed:

- What did you do?

run  this command on branch-4.6
mvn test -Dtest=DoubleByteBufTest

- What did you expect to see?

test passes

- What did you see instead?
```
Running org.apache.bookkeeper.util.DoubleByteBufTest
Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.153 sec <<< FAILURE! - in org.apache.bookkeeper.util.DoubleByteBufTest
testReadableBytes(org.apache.bookkeeper.util.DoubleByteBufTest)  Time elapsed: 0.013 sec  <<< FAILURE!
java.lang.AssertionError: expected:<256> but was:<192>
	at org.apache.bookkeeper.util.DoubleByteBufTest.testReadableBytes(DoubleByteBufTest.java:193)

```

**Comment by sijie** [comment]
@eolivelli can you diff the difference between branch?

**Comment by eolivelli** [comment]
@sijie see #1002 diff

**Comment by sijie** [comment]
okay I think the problem is there is a `DoubleByteBuffer` change introduced in #824 for 4.7, it fixes readableBytes and added the testReadableBytes test case. This change was not at branch-4.6, but we applied some other `DoubleByteBuffer` changes today in #996, which added the `testReadableBytes` but without bring the change in.

**Comment by eolivelli** [comment]
good catch !
