### ISSUE TITLE
grpc port 4181 not listening

### ISSUE THREAD

**Issue by hiscal2015** [apache/bookkeeper#1882]
bk version: 4.7.3

bk_server.conf has storageserver.grpc.port=4181 defined, but port is not listening, is this expected? Thanks.
```
### Grpc Server ###

# the grpc server port to listen on. default is 4181
storageserver.grpc.port=4181
```

**Comment by sijie** [comment]
@hiscal2015 

these settings belong to table service. table service is only enabled when https://github.com/apache/bookkeeper/blob/master/conf/bk_server.conf#L97 is enabled.

**Comment by sijie** [comment]
@hiscal2015 I see. that's because the metadata is not formatted yet. so the table service is not started correctly. we are currently working on the documentation for the table service. I would suggest waiting for 4.9.0 (which would come out in 1~2 weeks) before trying this feature out, till then we will have better documentation for this part.

**Comment by hiscal2015** [comment]
@sijie Thanks for clarifying.
