### ISSUE TITLE
Failed to download twitter maven repo dependencies

### ISSUE THREAD

**Issue by zymap** [apache/bookkeeper#1962]
**BUG REPORT**

When compiling using maven, there are some twitter maven repo can't download.
The dependencies are used by twitter-science-provider module.

**Comment by zymap** [comment]
Can set ~/.m2/setting.xml using proxy:
```
<proxies>
    <proxy>
      <id>ss</id>
      <active>true</active>
      <protocol>http</protocol>
     <!-- <protocol>socks</protocol> -->
      <!-- <username>username</username> -->
      <!-- <password>password</password> -->
      <host>127.0.0.1</host>
      <port>1087</port>
      <!-- <nonProxyHosts>local.net|some.host.com</nonProxyHosts> -->
    </proxy>
  </proxies>
```

**Comment by eolivelli** [comment]
@sijie  @yzang 
do we need to support 'twitter-science-provider' in Community builds ?
I guess they are in use only at Twitter

**Comment by sijie** [comment]
> do we need to support 'twitter-science-provider' in Community builds ?

I think it can still be built as part of `bookkeeper-all` distributions. but I don't think we should build twitter providers in normal processes. because 1) some of the twitter dependencies are only in twitter maven repo, but not at maven center. it causes problems for our CI builds; 2) twitter providers are not very popular as the other two modules - prometheus and codahale. 

so I would suggest exclude them from normal build and only build at part of bookkeeper-all. it will also reduce the build time for most of developers.
