### ISSUE TITLE
Implement a method to get all the Bookies

### ISSUE THREAD

**Issue by mino181295** [apache/bookkeeper#2114]
**FEATURE REQUEST**

I'm building a dashboard for Bookkeeper and I need a method to retrive from `BookKeeper` all the available Bookies including the down ones.

I have found `BookKeeper#getBookieInfo` and `BookKeeperAdmin#getAvailableBookies` but I didn't find a proper way to get the `BookieSocketAddress` inside the Zookeeper path `/ledgers/cookies`.

The workaround that I have right now is to access directly Zookeeper in this way:
```
Collection<BookieSocketAddress> result = new ArrayList<>();

Stat stat = zkClient.exists(BK_LEDGERS_PATH, true);
if (stat == null) {
    return result;
}
List<String> bkCookies = zkClient.getChildren(BK_LEDGERS_PATH + "/cookies", false);
if (bkCookies == null) {
    return result;
}
for (String bookieAddress : bkCookies) {
    result.add(new BookieSocketAddress(bookieAddress));
}
```

I would be happy to contribute to this patch if you give me some hints.

**Comment by eolivelli** [comment]
please add some link to your current code and how you are using BK client.

**Comment by mino181295** [comment]
This is my current project https://github.com/diennea/bookkeeper-visual-manager/

And in this class I get connected to `BookKeeper` client and `BookKeeperAdmin` 
https://github.com/diennea/bookkeeper-visual-manager/blob/master/src/main/java/org/bookkeepervisualmanager/bookkeeper/BookkeeperManager.java

**Comment by eolivelli** [comment]
@mino181295 I would add a new method
`RegistrationClient#getAllKnowBookies()`
that returns the list of all know bookies
and implement it in ZK metadata driver (ZKRegistrationClient).

for etcd we can return an empty list an log an error and create a new issue

The alternative  is to add a listCookies() method in RegistrationManager, I would prefer the first option because RegistrationClient we are talking about a client-side feature (that is the ability to discover dead bookies)

@sijie @jvrao  @reddycharan how does it sound to you ?

**Comment by jvrao** [comment]
We are working on something like this at Salesforce and we can commit to community soon. Basically we will be adding network location to the cookie and the client reads the persistent bookies (cookie) and ephemeral znodes(booke lease) to determine down bookies and also to learn the network location of active bookies for placement.

**Comment by eolivelli** [comment]
@jvrao good to hear that we are working on overlapping topics 

do you think that this simpler API will be useless with your future change?

This approach works with every version of BK (I guess yours too, even with old bookies).

I don't want to duplicate work or code. In theory it is better to have only one way to achieve a single goal.

We can send this little patch out for review, so that you can take a look.

**Comment by mino181295** [comment]
@jvrao I have submitted a draft PR. Can you take a look and see if it fits your needs?

**Comment by eolivelli** [comment]
@mino181295 @jvrao needs something more complex.
He wants to apply advanced placement strategies based on fault zones (datacenters/regions)

It is just important that your fix does not interfere with the other changes coming from SF
