### ISSUE TITLE
Limit the scan rate of entry log

### ISSUE THREAD

**Issue by codelipenghui** [apache/bookkeeper#2395]
**FEATURE REQUEST**

When bookies doing entry log compaction, the bookie will scan the entry log and rewrite the data that not yet deleted to the new entry log. It's better to add a limiter for the scanner to limit the read entry rate and read bytes rate of the old entry log.
Currently, the `compactionRateByBytes` and the `compactionRateByEntries` are limit the entry readding not limit the entry reading. So it's better to split the configurations into two part: `compactionWriteRateByBytes` and `compactionReadRateByBytes`. So that we can control both the entry read rate and entry readd rate.

**Comment by eolivelli** [comment]
Can we find a better name?

The new name looks like a typo :)

**Comment by codelipenghui** [comment]
@eolivelli How about `compactionWriteRateByBytes` and `compactionReadRateByBytes` ?

**Comment by eolivelli** [comment]
@codelipenghui  yeah. Those names sound really better

**Comment by hangc0276** [comment]
After deep into the compaction code, i found there is no need to divide  `compactionRateByBytes` into `compactionWriteRateByBytes` and `compactionReadRateByBytes`
https://github.com/apache/bookkeeper/blob/abf1a96e38bb74f7f7a47e9b6f2b337bd07d622f/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/EntryLogger.java#L1009-L1051

The reason is
1. The entry log scanner will just read each entry's metadata and decide whether to replicate it. If no need to replicate, it will skip the entry data. So there will be no heavy read data effects.
2. The read entry from entry log and write to new entry log logic is in a while loop. Currently, we throttle on write entry side, it will also throttle the entry read.

**Comment by shoothzj** [comment]
closed by stale, feel free to reopen it.
