### ISSUE TITLE
Bookkeeper TLS upgrade

### ISSUE THREAD

**Issue by ShPrajpati** [apache/bookkeeper#2546]
I run a bookkeeper cluster that is backend for pulsar, it has no TLS and I want to turn TLS on specificallu using mTLS without bringing pulsar down. Is there a way I can achieve that?

**Comment by dlg99** [comment]
@ShPrajpati it's been awhile since I dealt with this, so please double-check / experiment on the dev cluster.

First, you need to enable TLS on the server side but allow connections from the clients without the TLS.
IIRC `tlsClientAuthentication=false` in server config does that 
Set the config options on teh server side and do rolling restart of the bookies, this should not affect clients (i.e. pulsar)

This is the test that roughly shows the configuration you want: https://github.com/apache/bookkeeper/blob/3a8f4b4d3e762ac24a0563eeaffd068efaab2b81/bookkeeper-server/src/test/java/org/apache/bookkeeper/tls/TestTLS.java#L465-L476

2nd, enable TLS on the client side (check pulsar docs, I guess). 

3rd, make sure everything works via TLS. Now you can disable non-tls clients on the server side

Please close the issue if this is no longer a problem

**Comment by shoothzj** [comment]
free feel to reopen it if you still have problem.
