### ISSUE TITLE
auto read only mode support multi disks

### ISSUE THREAD

**Issue by leizhiyuan** [apache/bookkeeper#3141]
**FEATURE REQUEST**

when diskUsageThreshold is full, the bookie will convert to read-only 

1. Please describe the feature you are requesting.

```


readOnlyModeEnabled | If all ledger directories configured are full, then support only read requests for clients. If “readOnlyModeEnabled=true” then on all ledger disks full, bookie will be converted to read-only mode and serve only read requests. Otherwise the bookie will be shutdown. By default this will be disabled.
-- | --



diskUsageThreshold | For each ledger dir, maximum disk space which can be used. Default is 0.95f. i.e. 95% of disk can be used at most after which nothing will be written to that partition. If all ledger dir partions are full, then bookie will turn to readonly mode if ‘readOnlyModeEnabled=true’ is set, else it will shutdown. Valid values should be in between 0 and 1 (exclusive).
-- | --


```

now, if we have one disk, ledger dirs  are l1,l2,l3,l4 it runs ok

but if we have two disks, one for l1,l2, the other for l3,l4, because of the difference of every entry, after run a long time, 

the usage of disk1 will be 95%, but the other maybe 80%, then `DiskChecker` will think `If all ledger dir partions are full`  this is not true, they will write more date to disk, then disk 1 will be 100%, and goes down.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have).
   Are you currently using any workarounds to address this issue?

should-have

3. Provide any additional detail on your proposed use case for this feature.

maybe the usage of any of the disk be 0.95, we can translate to read-only, or we can translate disk1 to read only, but disk2 can be written

**Comment by eolivelli** [comment]
I understand the problem.
Unfortunately this is quite hard to implement because the client has no knowledge of the fact that the bookie has multiple disks and also the mapping between a ledger and the disk depends on the configuration and especially the implementation of the Storage.
For for instance a Bookie may be readonly for one ledger and not for the next ledgerid.

Currently the bookie advertises its read only status, this way clients don't choose it for new ledgers (or new segments)

Even by using an alternative mechanism to advertise the read only status (for instance a new error code while writing), that piece of information won't be useful for subsequent ledgers.

We will have to be much creative to implement this feature

**Comment by leizhiyuan** [comment]
> 
Thanks for your reply, what about if we add an alternative strategy  in bookkeeper.conf , which users can config it

`
if ** any ** one of disk full, we will convert bookie to read only
`

where default is all of ledgers partition are full.

**Comment by gaozhangmin** [comment]
> > 
> 
> Thanks for your reply, what about if we add an alternative strategy in bookkeeper.conf , which users can config it
> 
> `if ** any ** one of disk full, we will convert bookie to read only`
> 
> where default is all of ledgers partition are full.

How about, If you configured multi disk, when there are some  disks which capacity is full, this disk should be  excluded while writing ledgers data, instead of transforming bookie to read only. @leizhiyuan
