### ISSUE TITLE
Compaction does not remove entry files when remaining file size <  Compaction Threshold

### ISSUE THREAD

**Issue by sourabhaggrawal** [apache/bookkeeper#3711]
**BUG REPORT**

***Describe the bug***
Whenever major or minor compaction runs, it does not remove the log files which has utilised more than threshold value. But only remove the files with usage < threshold.

I am seeing high disk usage in ledger directory in 3 bookie cluster, all 3 nodes have couple of log files with size 1.1GB which is the default max entry log file size before it creates a new one. 
As per the documentation [here](https://bookkeeper.apache.org/docs/reference/config/) for Major and Minor Compaction, it is supposed to delete the log files when remaining log file size reaches below threshold.
When trying to debug this in code found that condition is checking for meta.Usage > threshold and ignore the meta file which is supposed to get deleted, what I feel it should be checking the meta.Remaining > Threshold. 
https://github.com/apache/bookkeeper/blob/dd80e967e7d3dc6873231a7bc04feaba83be54c3/bookkeeper-server/src/main/java/org/apache/bookkeeper/bookie/GarbageCollectorThread.java#L573

***To Reproduce***

***Expected behavior***
- Compaction should have removed the file if remaining file size < threshold.

***Screenshots***

<img width="1431" alt="Screenshot 2022-12-22 at 1 02 33 PM" src="https://user-images.githubusercontent.com/70515711/209081185-ed9723f2-06fa-4974-8c42-4d9ddbb13e10.png">

***Additional context***

**Comment by dlg99** [comment]
> When trying to debug this in code found that condition is checking for meta.Usage > threshold and ignore the meta file which is supposed to get deleted, what I feel it should be checking the meta.Remaining > Threshold.

meta.remaining is bytes. Threshold is a cutoff utilization (as percentage), meta.usage is meta.remainingSize / meta.totalSize.
remainingSize is the size used by ledgers/entries that are live (not deleted).
As the docs say, `For those entry log files whose remaining size **percentage** reaches below this threshold will be compacted`

Let's say total size of the entry log is 1000 Mbytes, remainingSize is 750 Mbytes. So the usage is 0.75
In case threshold set to 0.6 the compaction won't be performed on this entry log because the usage > threshold. 

The logic there is the i/o is not free and rewrite of 750Mbytes to free up a bit of space will be a perf hit on the bookie. If the disk space is a concern and the perf is not, you can set the threshold higher (0.8 or so) and this log will be compacted.

**Comment by sourabhaggrawal** [comment]
Thanks for helping me understand it more @dlg99 , I will close the issue.
