### ISSUE TITLE
Dirty data risk in ledger recovery.

### ISSUE THREAD

**Issue by thetumbled** [apache/bookkeeper#4226]
Discuss link: https://lists.apache.org/thread/y31v08js1rvdodyhxg5wcj0h3qjlxlcw

Copy from email:
    I have a question about the design of ledger recovery. According to the article https://medium.com/splunk-maas/apache-bookkeeper-insights-part-2-closing-ledgers-safely-386a399d0524, we are generous with positive results in recovery read, that is we will think an entry as recovable as soon as there is a positive results, instead of waiting for AQ positive results.
    I wonder whether we have the risk of dirty data (data duplication). For example, we may have config 3 3 2, and entry0 reach AQ copies, entry1 has only one copy in bookie1, entry2 do not exist at all. So when we start to recovery this ledger, we will think entry0 as recovable for sure. But when we examine whether entry1 is recovable, we may think it as recovable if we ask bookie1 and it reply positive, or we may think it as unrecovable if we receive negative result from bookie2 and bookie3. But as the client do not receive AQ successful reply, the client think that it fail to write entry1, and may try to write the same data again, which result into data duplication problem.

**Comment by thetumbled** [comment]
Could you help to answer this question?, thanks a lot. @Vanlightly @eolivelli @hangc0276 @merlimat

**Comment by Vanlightly** [comment]
Any system without dedup logic is susceptible to this. An application writing to bookies (via the client) could have its connections broken and despite entry1 being written successfully to AQ bookies, it never found that out, and so creates a new ledger and writes the data again. This really comes down to the fact that the BookKeeper protocol doesn't have dedup logic, via sequence numbers, in its protocol like Pulsar and Kafka do for example. Pulsar clients can resend writes to Pulsar brokers without duplicating payloads due to the dedup logic.

**Comment by thetumbled** [comment]
> Any system without dedup logic is susceptible to this. An application writing to bookies (via the client) could have its connections broken and despite entry1 being written successfully to AQ bookies, it never found that out, and so creates a new ledger and writes the data again. This really comes down to the fact that the BookKeeper protocol doesn't have dedup logic, via sequence numbers, in its protocol like Pulsar and Kafka do for example. Pulsar clients can resend writes to Pulsar brokers without duplicating payloads due to the dedup logic.

Make sense, thanks a lot.
