### ISSUE TITLE
ZKRegistrationClient watch error.

### ISSUE THREAD

**Issue by thetumbled** [apache/bookkeeper#4253]
**BUG REPORT**

***Describe the bug***
The implementation is not consistent with the description of method `
org.apache.bookkeeper.client.BookKeeperAdmin#watchWritableBookiesChanged`.

We expect that when the available list of bookies changes, we can trigger the listener. But actually, when i register a listener, the listener is triggered immediately without any bookies changes.
Test code:
```
package org.example.Bookie;

import java.io.IOException;
import java.util.concurrent.CountDownLatch;

import org.apache.bookkeeper.client.BKException;
import org.apache.bookkeeper.client.BookKeeper;
import org.apache.bookkeeper.client.BookKeeperAdmin;


public class BookieAdmin {
    public static void doSomething(CountDownLatch latch) {
        System.out.println("Hello World");
        latch.countDown();
    }

    public static void main(String[] args) throws BKException, IOException, InterruptedException {
        String zkConnectStringForTest = "XXX:2181";
        BookKeeper bk = new BookKeeper(zkConnectStringForTest);
        BookKeeperAdmin admin = new BookKeeperAdmin(bk);
        CountDownLatch latch = new CountDownLatch(2);
        System.out.println(admin.getAvailableBookies());
        admin.watchWritableBookiesChanged(bookies -> doSomething(latch));
        admin.watchReadOnlyBookiesChanged(bookies -> doSomething(latch));
        latch.await();
        admin.close();
        bk.close();
    }
}

```
<img width="320" alt="image" src="https://github.com/apache/bookkeeper/assets/52550727/47c8a566-1c67-4959-97ec-fb5abc4dcc26">

And i review the implementation of `org.apache.bookkeeper.discover.ZKRegistrationClient`, i do see the logic that trigger the bug describe above. I wonder whether it is a implementation error or a misleading feature?
Could you help to solve this problem? thanks. @hangc0276 @horizonzy @eolivelli

**Comment by shoothzj** [comment]
When you register the listener, it will fire current list of bookie. I think it's a feature. Feel free to reopen it.

**Comment by thetumbled** [comment]
> When you register the listener, it will fire current list of bookie. I think it's a feature. Feel free to reopen it.

Ok, someone may expect to receive notification once he register the callback.
But there are more than such problem with class `ZKRegistrationClient`. For example, the doc describe that 
```
     * Notify when the available list of bookies changes.
     * This is a one-shot notification. To receive subsequent notifications
     * the listener must be registered again.
```
in `org.apache.bookkeeper.client.BookKeeperAdmin#watchWritableBookiesChanged`.

But actually, we do not remove the listener after we trigger the listener, so we will trigger the listener infinitely.

**Comment by eolivelli** [comment]
I think that we should not put any requirements about this point.

In a distributed environment many sequences of events may "happen" and it is not guaranteed (for ZK for also for many other systems, due to the intrinsic nature of distributed systems)  that you observe all the events, the only real guarantee is that eventually the local node is notified and it is able to build a local consistent view of the metadata.

I don't think it is a problem if the callback is called even if nothing changed, it is more like a feature.

Think about this case:
- state A
- client connects and sets a watch
- client disconnects
- state B
- state changes to C
- state changes to B
- client reconnects
- the client is notified that "something happened" and then it can see that the current state is B

The client never sees that the "state" changed from B to C and then back to B, but it is important that it is notified that the state changed and it is now B (and not A)
