### ISSUE TITLE
Move backward compatibility tests into a separate module

### ISSUE THREAD

**Issue by sijie** [apache/bookkeeper#466]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Currently the backward compatibility tests are part `bookkeeper-server`. It would be good to move them out of current `bookkeeper-server` into a separate module. This module doesn't need to be deployed to artifact.

This proposal is to have a separate `tests` module and organize `backward compatibility` and other integrate tests there.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

*nice-to-have*

3. Provide any additional detail on your proposed use case for this feature.

N/A

**Comment by ivankelly** [comment]
I was thinking about these recently, and i think it would be better to change how compat testing is done completely. Rather than having something like unit tests, we should be doing integration tests. We should spin up a bunch of docker instances with different versions of bookkeeper and verify that.
1. Different client versions can read and write
2. Upgrading doesn't break things.

The thing that's currently there, with shading and relocation is a hack and a nightmare to add new tests to.

**Comment by sijie** [comment]
@ivankelly yes exactly. I had the same feeling with you - backward compatible tests are a nightmare. I like your idea to use docker instances to do integration tests.

for this change, I would try to move them out first. later on, we can make tests directory contains all the stuffs for running integration tests.
